package com.employeeclient.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-12T21:26:35.937-06:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://service.employeeprovider.com/", name = "EmployeeProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeProvider {

    @WebMethod
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.AddEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.employeeclient.proxy.Employee arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.UpdateEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findByName", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.FindByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.employeeclient.proxy.Employee> findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findEmployee", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.FindEmployee")
    @ResponseWrapper(localName = "findEmployeeResponse", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.FindEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.employeeclient.proxy.Employee findEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "removeEmployee", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.RemoveEmployee")
    @ResponseWrapper(localName = "removeEmployeeResponse", targetNamespace = "http://service.employeeprovider.com/", className = "com.employeeclient.proxy.RemoveEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean removeEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        com.employeeclient.proxy.Employee arg0
    );
}
