
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.employeeclient.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-12T21:26:35.897-06:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "EmployeeProviderService",
                      portName = "EmployeeProviderPort",
                      targetNamespace = "http://service.employeeprovider.com/",
                      wsdlLocation = "http://localhost:9090/SOAP-webservice/employee?wsdl",
                      endpointInterface = "com.employeeclient.proxy.EmployeeProvider")
                      
public class EmployeeProviderPortImpl implements EmployeeProvider {

    private static final Logger LOG = Logger.getLogger(EmployeeProviderPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.employeeclient.proxy.EmployeeProvider#addEmployee(com.employeeclient.proxy.Employee arg0)*
     */
    public java.lang.Boolean addEmployee(com.employeeclient.proxy.Employee arg0) { 
        LOG.info("Executing operation addEmployee");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.employeeclient.proxy.EmployeeProvider#updateEmployee(int arg0)*
     */
    public java.lang.Boolean updateEmployee(int arg0) { 
        LOG.info("Executing operation updateEmployee");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.employeeclient.proxy.EmployeeProvider#findByName(java.lang.String arg0)*
     */
    public java.util.List<com.employeeclient.proxy.Employee> findByName(java.lang.String arg0) { 
        LOG.info("Executing operation findByName");
        System.out.println(arg0);
        try {
            java.util.List<com.employeeclient.proxy.Employee> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.employeeclient.proxy.EmployeeProvider#findEmployee(int arg0)*
     */
    public com.employeeclient.proxy.Employee findEmployee(int arg0) { 
        LOG.info("Executing operation findEmployee");
        System.out.println(arg0);
        try {
            com.employeeclient.proxy.Employee _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.employeeclient.proxy.EmployeeProvider#removeEmployee(com.employeeclient.proxy.Employee arg0)*
     */
    public java.lang.Boolean removeEmployee(com.employeeclient.proxy.Employee arg0) { 
        LOG.info("Executing operation removeEmployee");
        System.out.println(arg0);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
