
package com.employeeclient.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-12T21:26:35.834-06:00
 * Generated source version: 3.2.1
 * 
 */
public final class EmployeeProvider_EmployeeProviderPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.employeeprovider.com/", "EmployeeProviderService");

    private EmployeeProvider_EmployeeProviderPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EmployeeProviderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EmployeeProviderService ss = new EmployeeProviderService(wsdlURL, SERVICE_NAME);
        EmployeeProvider port = ss.getEmployeeProviderPort();  
        
        {
        System.out.println("Invoking addEmployee...");
        com.employeeclient.proxy.Employee _addEmployee_arg0 = null;
        java.lang.Boolean _addEmployee__return = port.addEmployee(_addEmployee_arg0);
        System.out.println("addEmployee.result=" + _addEmployee__return);


        }
        {
        System.out.println("Invoking updateEmployee...");
        int _updateEmployee_arg0 = 0;
        java.lang.Boolean _updateEmployee__return = port.updateEmployee(_updateEmployee_arg0);
        System.out.println("updateEmployee.result=" + _updateEmployee__return);


        }
        {
        System.out.println("Invoking findByName...");
        java.lang.String _findByName_arg0 = "";
        java.util.List<com.employeeclient.proxy.Employee> _findByName__return = port.findByName(_findByName_arg0);
        System.out.println("findByName.result=" + _findByName__return);


        }
        {
        System.out.println("Invoking findEmployee...");
        int _findEmployee_arg0 = 0;
        com.employeeclient.proxy.Employee _findEmployee__return = port.findEmployee(_findEmployee_arg0);
        System.out.println("findEmployee.result=" + _findEmployee__return);


        }
        {
        System.out.println("Invoking removeEmployee...");
        com.employeeclient.proxy.Employee _removeEmployee_arg0 = null;
        java.lang.Boolean _removeEmployee__return = port.removeEmployee(_removeEmployee_arg0);
        System.out.println("removeEmployee.result=" + _removeEmployee__return);


        }

        System.exit(0);
    }

}
